FROM python:alpine 

WORKDIR /docker-flask-app

RUN apk update && apk add --no-cache\
    gcc \
    python3-dev \
    musl-dev \
    postgresql-dev \
    build-base \
    linux-headers \ 
    pcre-dev

COPY ./requirements.txt ./
COPY ./uwsgi-app.ini ./
RUN pip install -r requirements.txt

COPY ./.env ./
COPY ./src ./src

ENV PYTHONPATH /docker-flask-app
RUN chmod -x src/app/app.py
CMD ["python", "src/app/app.py"]