version: '3'
services:
  redis:
    image: 'redis'
  web:
    container_name: flask-app-prod
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/docker-flask-app/src
  postgres_db:
    container_name: postgres
    image: postgres:10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin 
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/db_create.sql:/docker-entrypoint-initdb.d/init.sql
         